### ISSUE TITLE
Unity 6000.0.45f1 freezes on Play after starting debugging via Cursor F5

### ISSUE THREAD

**Issue by SyaoranChang** [JaneySprings/DotRush#62]
Hi,

My software versions:

    Unity: 6000.0.45f1

    Cursor: 1.0

    DotRush: 25.5.149

Expected Behavior:
I press F5 in Cursor to start debugging, then click Play in Unity. The game runs normally and I can hit breakpoints.

Issue:
I press F5 in Cursor to start debugging, then click Play in Unity. Unity freezes and gets stuck on “Reloading Domain” with an infinite loading screen.

![Image](https://github.com/user-attachments/assets/bc8cb35d-4460-46da-ae28-6b6de57c796a)

Current Workaround:
To avoid the freeze, I have to follow this exact sequence each time:

1.Press Stop Debugging in Cursor.

2.Press Play in Unity.

3.Then press F5 (Start Debugging) in Cursor.

**Comment by JaneySprings** [comment]
Hi, @SyaoranChang ! Can you check your cursor window when Unity freezes? Maybe there is any exception? Debugging is paused or it looks like everything is ready and waiting for a breakpoint?

**Comment by SyaoranChang** [comment]
Hi, I suspect that the debugger might have already hit a breakpoint when Unity starts playing.
However, when I press F5 again in Cursor to try resuming or stepping out of the breakpoint, nothing happens — the Unity editor remains stuck on “Reloading Domain”.

I checked the message window at the bottom of the Unity Editor, but there were no error messages or logs that seem related to this issue.
![Image](https://github.com/user-attachments/assets/9a954cb8-c9cf-45de-a30d-795129a1a861)

**Comment by JaneySprings** [comment]
Am I correct in understanding that you have a stop in Cursor after running debug? Is this an exception? Is there any data in the Watch window?

**Comment by SyaoranChang** [comment]
Main Issue:
When I press F5 (Start Debugging) in Cursor first, and then press Play in Unity, the editor gets stuck on "Reloading Domain" and never finishes loading.

Workaround:
To avoid Unity getting stuck on "Reloading Domain", I need to:
    Press Stop Debugging in Cursor.
    Wait until the Reloading Domain window in Unity closes.
    Then press F5 (Start Debugging) in Cursor again.
Only then can I start debugging properly.

I created a new empty Unity project (same version: 6000.0.45f1) and tested debugging with Cursor. 
In the new project, I did not encounter the "Reloading Domain" freeze issue, which suggests that something specific in my main project is causing the problem.

**Comment by SyaoranChang** [comment]
New Reproducible Issue in Empty Project:
I discovered another issue that can be reproduced even in a brand-new empty Unity project. I will outline the steps to reproduce it below.

Repro Steps (in empty Unity project):
    1.In Cursor, press F5 Starting Debugging.
    2.In Unity, create a new Animation Clip.
    3.Click on the Animation Clip file to open the Animation Editor.
   4.In Cursor, an error appears related to UnityEngine.ExitGUIException.

Expected:
No exception should occur when opening an Animation Clip.

Actual:
Cursor displays a UnityEngine.ExitGUIException error when the Animation window is opened.

> Exception has occurred: UnityEngine.ExitGUIException
Exception of type 'UnityEngine.ExitGUIException' was thrown.
    at UnityEngine.GUIUtility.ExitGUI () [0x00006] in <82bd4bb4cad84dbeb1ef8da9d79aba99>:line 0
    at UnityEditorInternal.AnimationWindowHierarchyGUI.DoAddCurveButton (UnityEngine.Rect rect, UnityEditorInternal.AnimationWindowHierarchyNode node, System.Int32 row) [0x00095] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditorInternal.AnimationWindowHierarchyGUI.DoNodeGUI (UnityEngine.Rect rect, UnityEditorInternal.AnimationWindowHierarchyNode node, System.Boolean selected, System.Boolean focused, System.Int32 row) [0x000ae] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditorInternal.AnimationWindowHierarchyGUI.OnRowGUI (UnityEngine.Rect rowRect, UnityEditor.IMGUI.Controls.TreeViewItem node, System.Int32 row, System.Boolean selected, System.Boolean focused) [0x00008] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.IMGUI.Controls.TreeViewController.DoItemGUI (UnityEditor.IMGUI.Controls.TreeViewItem item, System.Int32 row, System.Single rowWidth, System.Boolean hasFocus) [0x000a1] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.IMGUI.Controls.TreeViewController.IterateVisibleItems (System.Int32 firstRow, System.Int32 numVisibleRows, System.Single rowWidth, System.Boolean hasFocus) [0x00149] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.IMGUI.Controls.TreeViewController.OnGUI (UnityEngine.Rect rect, System.Int32 keyboardControlID) [0x00458] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditorInternal.AnimationWindowHierarchy.OnGUI (UnityEngine.Rect position) [0x0001a] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.AnimEditor.HierarchyOnGUI () [0x0013f] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.AnimEditor.OnAnimEditorGUI (UnityEditor.EditorWindow parent, UnityEngine.Rect position) [0x00147] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.AnimationWindow.OnGUI () [0x00047] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition) [0x000c2] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.DockArea.DrawView (UnityEngine.Rect dockAreaRect) [0x00001] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.DockArea.OldOnGUI () [0x001cb] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) [0x002b9] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) [0x000c4] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) [0x00015] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) [0x00009] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) [0x00029] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) [0x0012a] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.IMGUIContainer.HandleEventBubbleUp (UnityEngine.UIElements.EventBase evt) [0x00009] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.CallbackEventHandler.HandleEventBubbleUpInternal (UnityEngine.UIElements.EventBase evt) [0x00000] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.EventDispatchUtilities.HandleEvent_BubbleUpHandleEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel, UnityEngine.UIElements.VisualElement element, System.Boolean disabled) [0x00022] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.EventDispatchUtilities.HandleEvent_BubbleUpAllDefaultActions (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel, UnityEngine.UIElements.VisualElement element, System.Boolean disabled, System.Boolean isCapturingTarget) [0x0003a] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.EventDispatchUtilities.HandleEventAcrossPropagationPathWithCompatibilityEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.EventBase compatibilityEvt, UnityEngine.UIElements.BaseVisualElementPanel panel, UnityEngine.UIElements.VisualElement target, System.Boolean isCapturingTarget) [0x00281] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.EventDispatchUtilities.PropagateEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel, UnityEngine.UIElements.VisualElement target, System.Boolean isCapturingTarget) [0x00022] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.EventDispatchUtilities.DispatchToCapturingElement (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel, System.Int32 pointerId, UnityEngine.Vector2 position) [0x0007e] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.EventDispatchUtilities.DispatchToCapturingElementOrElementUnderPointer (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel, System.Int32 pointerId, UnityEngine.Vector2 position) [0x0000b] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.PointerEventBase`1[T].Dispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) [0x00014] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel) [0x00072] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) [0x00049] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) [0x0001f] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) [0x00136] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) [0x0003d] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) [0x0001a] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) [0x00001] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) [0x00083] in <82bd4bb4cad84dbeb1ef8da9d79aba99>:line 0

**Comment by JaneySprings** [comment]
If I add this exception to ignore and it is skipped, will it solve your problem?
It can't be done right now, but I'll add this feature.

**Comment by SyaoranChang** [comment]
This might resolve the Animation editor-related exception, but I'm not sure whether it's related to the "Reloading Domain hangs after pressing Play in Unity while debugging is active" issue.

**Comment by JaneySprings** [comment]
I figured out what the problem was. I'm loading too many assemblies, including Unity libraries, which contain a lot of unhandled exceptions. We only need to load `Assembly-CSharp.dll` (hopefully it can't be renamed).

https://github.com/JaneySprings/DotRush/blob/5dcf0f67034e30866b924fe0b0450e0b4ff34681/src/DotRush.Debugging.Unity/Extensions/MonoExtensions.cs#L92

**Comment by JaneySprings** [comment]
Fixed in `25.6.159`
@SyaoranChang, can you test it?

**Comment by SyaoranChang** [comment]
> Fixed in `25.6.159` [@SyaoranChang](https://github.com/SyaoranChang), can you test it?

I just tested version 25.6.159
Fixed:
I press F5 in Cursor to start debugging, then click Play in Unity. Unity freezes and gets stuck on “Reloading Domain” with an infinite loading screen.

Still occurs:
Cursor displays a UnityEngine.ExitGUIException error when the Animation window is opened.

**Comment by JaneySprings** [comment]
An `UnhandledException` happens here, which we should see anyway. I don't know how to do it better. How critical is this for you? I can add another exception ignore here, as has already been done with `ThreadAbort`, but I'm not sure if we should always skip such an error.

![Image](https://github.com/user-attachments/assets/a88a98eb-9688-4e96-ad39-5db19083dd54)

**Comment by SyaoranChang** [comment]
Just confirmed that the Animator Controller also triggers a similar ExitGUIException error.
This might be because I often have Debugging enabled while opening both Animation Clips and the Animator Controller.
I also sometimes need to debug the behavior scripts attached to states within the Animator Controller.

Pressing F5 allows me to continue, but the issue remains somewhat disruptive.

Exception When I open Animator Controller:
> Exception has occurred: UnityEngine.ExitGUIException
Exception of type 'UnityEngine.ExitGUIException' was thrown.
    at UnityEngine.GUIUtility.ExitGUI () [0x00006] in <82bd4bb4cad84dbeb1ef8da9d79aba99>:line 0
    at UnityEditor.ProjectBrowser.OpenAssetSelection (System.Int32[] selectedInstanceIDs) [0x00029] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.ProjectBrowser.OpenListAreaSelection () [0x0006a] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.ProjectBrowser.ListAreaItemSelectedCallback (System.Boolean doubleClicked) [0x000c4] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.ObjectListArea.SetSelection (System.Int32[] selectedInstanceIDs, System.Boolean doubleClicked) [0x0001e] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.ObjectListArea+LocalGroup.HandleMouseWithDragging (UnityEditorInternal.InternalEditorUtility+AssetReference& assetReference, System.Int32 controlID, UnityEngine.Rect rect) [0x00092] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.ObjectListArea+LocalGroup.DrawItem (UnityEngine.Rect position, UnityEditor.FilteredHierarchy+FilterResult filterItem, UnityEditor.BuiltinResource builtinResource, System.Boolean isFolderBrowsing) [0x01026] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.ObjectListArea+LocalGroup.DrawInternal (System.Int32 beginIndex, System.Int32 endIndex, System.Single yOffset) [0x0014e] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.ObjectListArea+Group.Draw (System.Single yOffset, UnityEngine.Vector2 scrollPos, System.Int32& rowsInUse) [0x0014f] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.ObjectListArea.HandleListArea () [0x0018e] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.ObjectListArea.OnGUI (UnityEngine.Rect position, System.Int32 keyboardControlID) [0x00155] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.ProjectBrowser.OnGUI () [0x001f1] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition) [0x000c2] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.DockArea.DrawView (UnityEngine.Rect dockAreaRect) [0x00001] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEditor.DockArea.OldOnGUI () [0x001cb] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) [0x002b9] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) [0x000c4] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) [0x00015] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) [0x00009] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) [0x00029] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) [0x0012a] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.IMGUIContainer.HandleEventBubbleUp (UnityEngine.UIElements.EventBase evt) [0x00009] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.CallbackEventHandler.HandleEventBubbleUpInternal (UnityEngine.UIElements.EventBase evt) [0x00000] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.EventDispatchUtilities.HandleEvent_BubbleUpHandleEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel, UnityEngine.UIElements.VisualElement element, System.Boolean disabled) [0x00022] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.EventDispatchUtilities.HandleEvent_BubbleUpAllDefaultActions (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel, UnityEngine.UIElements.VisualElement element, System.Boolean disabled, System.Boolean isCapturingTarget) [0x0003a] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.EventDispatchUtilities.HandleEventAcrossPropagationPathWithCompatibilityEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.EventBase compatibilityEvt, UnityEngine.UIElements.BaseVisualElementPanel panel, UnityEngine.UIElements.VisualElement target, System.Boolean isCapturingTarget) [0x00281] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.EventDispatchUtilities.PropagateEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel, UnityEngine.UIElements.VisualElement target, System.Boolean isCapturingTarget) [0x00022] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.EventDispatchUtilities.DispatchToCachedElementUnderPointerOrPanelRoot (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel, System.Int32 pointerId, UnityEngine.Vector2 position) [0x00037] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.EventDispatchUtilities.DispatchToCapturingElementOrElementUnderPointer (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel, System.Int32 pointerId, UnityEngine.Vector2 position) [0x0001a] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.PointerEventBase`1[T].Dispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) [0x00014] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel) [0x00072] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) [0x00049] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) [0x0001f] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) [0x00136] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) [0x0003d] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) [0x0001a] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) [0x00001] in <bbdbd655bd8e43829a8cd81691bef4c8>:line 0
    at UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) [0x00083] in <82bd4bb4cad84dbeb1ef8da9d79aba99>:line 0

**Comment by JaneySprings** [comment]
I have added this exception to the ignore list. You can try it now in the new version.

**Comment by SyaoranChang** [comment]
I just checked the version, and it seems to still be version 25.6.159.
Maybe I need to wait a little longer?

![Image](https://github.com/user-attachments/assets/55a6706d-f1ab-4300-a737-a3e0b5e030cf)

**Comment by JaneySprings** [comment]
It seems like it should be available:

https://marketplace.visualstudio.com/items?itemName=nromanov.dotrush
![Image](https://github.com/user-attachments/assets/7823e811-b1f4-4165-a4b9-9bb218d278fc)

You can try to download VSIX from [OpenVSX](https://open-vsx.org/extension/nromanov/dotrush) or [GitHub Release page](https://github.com/JaneySprings/DotRush/releases/tag/2025.06-service2):

**Comment by SyaoranChang** [comment]
I just tested version 25.6.160.

Fixed:
I press F5 in Cursor to start debugging, then click Play in Unity. Unity freezes and gets stuck on “Reloading Domain” with an infinite loading screen.
Cursor displays a UnityEngine.ExitGUIException error when the Animation window is opened.

While using this plugin, I also encountered another issue — not sure if it's something that could be fixed?
After pressing F5 to start debugging, then I close Unity, the following exception occurs:

UnityEngine.CoreModule.dll
> Exception has occurred: UnityEngine.UnityException
GetPtrFromInstanceID is not allowed to be called while application is terminating.
    at (wrapper managed-to-native) UnityEngine.Object.GetPtrFromInstanceID(int,System.Type,bool&)
    at UnityEngine.Object+MarshalledUnityObject.MarshalFromInstanceId[T] (T obj) [0x0001b] in <844019a3a067481c8d9cb70c7a2ba447>:line 0
    at UnityEngine.Object+MarshalledUnityObject.MarshalNotNull[T] (T obj) [0x00028] in <844019a3a067481c8d9cb70c7a2ba447>:line 0
    at UnityEngine.Object+MarshalledUnityObject.Marshal[T] (T obj) [0x00016] in <844019a3a067481c8d9cb70c7a2ba447>:line 0
    at UnityEngine.Object.DestroyImmediate (UnityEngine.Object obj, System.Boolean allowDestroyingAssets) [0x00000] in <844019a3a067481c8d9cb70c7a2ba447>:line 0
    at UnityEngine.Object.DestroyImmediate (UnityEngine.Object obj) [0x00003] in <844019a3a067481c8d9cb70c7a2ba447>:line 0
    at UnityEditor.EditorGUIUtility+<>c__DisplayClass49_0.<RegisterResourceForCleanupOnDomainReload>b__0 (System.Object sender, System.EventArgs e) [0x00001] in <4d62aeff85f745648163b49ed30bba78>:line 0
    at (wrapper delegate-invoke) <Module>.invoke_void_object_EventArgs(object,System.EventArgs)
    at System.AppDomain.DoDomainUnload () [0x00008] in <314938d17f3848e8ac683e11b27f62ee>:line 0

**Comment by JaneySprings** [comment]
Just press 'Continue' in cursor. This can also be fixed, but it seems that the `UnityException` type can be used somewhere else.
